package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 15-review-regressions.jmx.
 * Conversion notes: see conversion-report.md (5 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx15ReviewRegressionsSimulation extends Simulation {

    // JMeter property pages; override with -Dpages=...
    private static final int PAGES = Integer.getInteger("pages", 2);

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://edge.example-regressions.test");

    // TestPlan > HTTP (ThreadGroup) > Credentials (CSVDataSet)
    private final FeederBuilder<String> credentialsFeeder = csv("creds.csv").circular();

    // TestPlan > Edge Values (ThreadGroup) > Backslash Delimited (CSVDataSet)
    private final FeederBuilder<String> backslashDelimitedFeeder = separatedValues("odd.csv", '\\').circular();

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > HTTP (ThreadGroup) > Login (OnceOnlyController)
    private final ChainBuilder login = exec(
        // Login (OnceOnlyController)
        doIf(session -> !session.contains("jmx2g_once_1")).then(
            exec(session -> session.set("jmx2g_once_1", true)),
            // Login (OnceOnlyController) > POST /login (HTTPSamplerProxy)
            http("POST /login").post("/login")
                .formParam("u", "#{username}")
        )
    );

    // TestPlan > HTTP (ThreadGroup) > Http (TransactionController)
    private final ChainBuilder http2 = exec(
        // Http (TransactionController)
        group("Http").on(
            // Http (TransactionController) > GET /browse (HTTPSamplerProxy)
            http("GET /browse").get("/browse")
        )
    );

    // TestPlan > HTTP (ThreadGroup) > Other (GenericController)
    private final ChainBuilder other = exec(
        // Other (GenericController)
        // Other (GenericController) > GET /other (HTTPSamplerProxy)
        http("GET /other").get("/other")
    );

    // TestPlan > Loops By Property (ThreadGroup) > Inner Forever By Property (LoopController)
    private final ChainBuilder innerForeverByProperty = exec(
        // Inner Forever By Property (LoopController)
        // TODO(jmx2gatling) #1 Loop count ${__P(inner,-1)} defaults to -1 (loop forever) and is converted as infinite; -Dinner is not read. Replace with repeat(...) if you pass a count [LoopController]
        // Original:
        //     ${__P(inner,-1)}
        forever().on(
            // Inner Forever By Property (LoopController) > GET /inner (HTTPSamplerProxy)
            http("GET /inner").get("/inner")
        )
    );

    // TestPlan > Loops By Property (ThreadGroup) > Pages By Property (LoopController)
    private final ChainBuilder pagesByProperty = exec(
        // Pages By Property (LoopController)
        repeat(PAGES).on(
            // Pages By Property (LoopController) > GET /page (HTTPSamplerProxy)
            http("GET /page").get("/page")
        )
    );

    // TestPlan > HTTP (ThreadGroup)
    private final ScenarioBuilder http3 = scenario("HTTP")
        .exec(
            // Thread group loop count
            repeat(3).on(
                // Cookies are cleared at each iteration, as in JMeter
                exec(flushCookieJar()),
                // CSV Data Set: Credentials (CSVDataSet)
                feed(credentialsFeeder),
                // Login (OnceOnlyController)
                login,
                // Http (TransactionController)
                http2,
                // Other (GenericController)
                other
            )
        );

    // TestPlan > Loops By Property (ThreadGroup)
    // TODO(jmx2gatling) #2 Loop count ${__P(loops,-1)} defaults to -1 (loop forever) and is converted as infinite; -Dloops is not read. Replace with repeat(...) if you pass a count [ThreadGroup]
    // Original:
    //     ${__P(loops,-1)}
    private final ScenarioBuilder loopsByProperty = scenario("Loops By Property")
        .exec(
            // Loop until the scheduler duration ends
            during(Duration.ofSeconds(60)).on(
                // Cookies are cleared at each iteration, as in JMeter
                exec(flushCookieJar()),
                // Inner Forever By Property (LoopController)
                innerForeverByProperty,
                // Pages By Property (LoopController)
                pagesByProperty
            )
        );

    // TestPlan > Edge Values (ThreadGroup)
    private final ScenarioBuilder edgeValues = scenario("Edge Values")
        .exec(
            // Cookies are cleared at each iteration, as in JMeter
            exec(flushCookieJar()),
            // CSV Data Set: Backslash Delimited (CSVDataSet)
            feed(backslashDelimitedFeeder),
            // Timers: Pacing (ConstantTimer), Huge Timer (ConstantTimer)
            pause(Duration.ofMillis(3000001000L)),
            // __RandomString for the request below
            exec(session -> session.set("jmx2g_fn_2", randomString(8, "abc"))),
            // __time for the request below
            exec(session -> session.set("jmx2g_fn_3", String.valueOf(System.currentTimeMillis() / 8L))),
            // GET /edges (HTTPSamplerProxy)
            // TODO(jmx2gatling) #3 AuthManager not converted; it applied to this sampler [AuthManager]
            // TODO(jmx2gatling) #4 CounterConfig not converted; it applied to this sampler [CounterConfig]
            // TODO(jmx2gatling) #5 Match number `99999999999` for `huge` is not a literal integer in range; using the first match [RegexExtractor]
            http("GET /edges").get("/edges/#{jmx2g_fn_2}/#{jmx2g_fn_3}")
                .check(regex("token=\"(\\w+)\"").find().withDefaultEl("#{fallbackToken}").saveAs("token"))
                .check(regex("marker=\"(\\w+)\"").find().withDefault("#{not-el}").saveAs("marker"))
                .check(regex("(x)").find().withDefault("none").saveAs("huge")),
            // Timers: Pacing (ConstantTimer)
            pause(Duration.ofMillis(1000)),
            // Collect item_1..item_N into a list for foreach
            exec(session -> session.set("jmx2g_series_4", collectSeries(session, "item_", 8, -1))),
            // Leading Zero Index (ForeachController)
            foreach("#{jmx2g_series_4}", "it").on(
                // Timers: Pacing (ConstantTimer)
                pause(Duration.ofMillis(1000)),
                // Leading Zero Index (ForeachController) > GET /item (HTTPSamplerProxy)
                http("GET /item").get("/item/#{it}")
            ),
            // Timers: Pacing (ConstantTimer)
            pause(Duration.ofMillis(1000)),
            // POST /ideographic (HTTPSamplerProxy)
            http("POST /ideographic").post("/ideographic")
                .body(StringBody("first line\u3000\nsecond line\u2003"))
        );

    {
        setUp(
            // Injection for TestPlan > HTTP (ThreadGroup)
            http3.injectOpen(atOnceUsers(1)),
            // Injection for TestPlan > Loops By Property (ThreadGroup)
            loopsByProperty.injectOpen(atOnceUsers(1)),
            // Injection for TestPlan > Edge Values (ThreadGroup)
            edgeValues.injectOpen(atOnceUsers(1))
        ).protocols(httpProtocol);
    }

    /** Equivalent of JMeter's __RandomString: {@code length} characters picked from {@code chars}. */
    private static String randomString(int length, String chars) {
        java.util.concurrent.ThreadLocalRandom random = java.util.concurrent.ThreadLocalRandom.current();
        StringBuilder out = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            out.append(chars.charAt(random.nextInt(chars.length())));
        }
        return out.toString();
    }

    /** The JMeter variable series prefix1, prefix2, ... as a list, the way a ForEach Controller reads it. */
    private static java.util.List<String> collectSeries(Session session, String prefix, int startExclusive, int endInclusive) {
        java.util.List<String> values = new java.util.ArrayList<>();
        for (int i = startExclusive + 1; endInclusive < 0 || i <= endInclusive; i++) {
            if (!session.contains(prefix + i)) {
                break;
            }
            values.add(session.getString(prefix + i));
        }
        return values;
    }
}
