package jmx2gatling.inventory;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import org.junit.jupiter.api.Test;

/**
 * The README's support matrix is rendered from {@link SupportMatrix}; this test keeps them in sync.
 * Run with {@code -Dgolden.update=true} to rewrite the README section.
 */
class ReadmeMatrixTest {

    private static final Path README = Path.of("README.md");
    private static final String START = "<!-- support-matrix:start (generated by ReadmeMatrixTest; do not edit by hand) -->";
    private static final String END = "<!-- support-matrix:end -->";

    static String render() {
        StringBuilder out = new StringBuilder();
        out.append("### Elements\n\n");
        out.append("Element types not listed are unsupported (TODO), except listeners, which are always ignored.\n\n");
        out.append("| JMeter element | Role | Support | Gatling |\n|---|---|---|---|\n");
        for (SupportMatrix.ElementEntry e : SupportMatrix.elements()) {
            out.append("| `").append(e.type()).append("` | ").append(role(e.kind())).append(" | ").append(e.status().label())
                .append(" | ").append(e.gatling().replace("|", "\\|")).append(" |\n");
        }
        out.append("\n### Functions\n\n");
        out.append("Functions not listed are unsupported: they stay in the request verbatim with a TODO.\n\n");
        out.append("| JMeter function | Support | Gatling |\n|---|---|---|\n");
        for (SupportMatrix.FunctionEntry f : SupportMatrix.functions()) {
            out.append("| `").append(f.name()).append("` | ").append(f.status().label()).append(" | ").append(f.gatling().replace("|", "\\|")).append(" |\n");
        }
        return out.toString();
    }

    private static String role(ElementKind kind) {
        return kind.name().toLowerCase(Locale.ROOT).replace('_', ' ');
    }

    @Test
    void readmeMatrixMatchesTheCode() throws IOException {
        String readme = Files.readString(README, StandardCharsets.UTF_8);
        int start = readme.indexOf(START);
        int end = readme.indexOf(END);
        assertTrue(start >= 0 && end > start, "README.md must contain the support-matrix markers");
        String current = readme.substring(start + START.length(), end);
        String expected = "\n" + render() + "\n";
        if (Boolean.getBoolean("golden.update")) {
            Files.writeString(README, readme.substring(0, start + START.length()) + expected + readme.substring(end), StandardCharsets.UTF_8);
            return;
        }
        assertEquals(expected, current, "README support matrix is stale; rerun with -Dgolden.update=true");
    }
}
