package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 11-properties-and-scheduler.jmx.
 * Conversion notes: see conversion-report.md (5 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx11PropertiesAndSchedulerSimulation extends Simulation {

    // JMeter property host; override with -Dhost=...
    private static final String HOST = System.getProperty("host", "load.example-props.test");

    // JMeter property duration; override with -Dduration=...
    private static final int DURATION = Integer.getInteger("duration", 300);

    // JMeter property users; override with -Dusers=...
    private static final int USERS = Integer.getInteger("users", 50);

    // JMeter property rampup; override with -Drampup=...
    private static final int RAMPUP = Integer.getInteger("rampup", 60);

    // JMeter property loops; override with -Dloops=...
    private static final int LOOPS = Integer.getInteger("loops", 10);

    // How long thread groups that looped forever in JMeter run (also the simulation's maxDuration); override with -DdurationSeconds=...
    private static final int DURATION_SECONDS = Integer.getInteger("durationSeconds", 600);

    // JMeter property threads; override with -Dthreads=...
    private static final int THREADS = Integer.getInteger("threads", 5);

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://" + HOST);

    // JMeter property threads; override with -Dthreads=...
    private static final String THREADS_2 = System.getProperty("threads", "5");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Steady Load (ThreadGroup)
    private final ScenarioBuilder steadyLoad = scenario("Steady Load")
        .exec(
            // Initial session values: user-defined variables and JMeter properties used in requests
            exec(session -> session
                .set("threads", THREADS_2)),
            // Loop until the scheduler duration ends
            during(Duration.ofSeconds(DURATION)).on(
                // Cookies are cleared at each iteration, as in JMeter
                exec(flushCookieJar()),
                // GET /steady (HTTPSamplerProxy)
                http("GET /steady").get("/steady"),
                exitHereIfFailed(),
                // GET /steady/next (HTTPSamplerProxy)
                http("GET /steady/next").get("/steady/next"),
                exitHereIfFailed()
            )
        );

    // TestPlan > Fixed Iterations (ThreadGroup)
    private final ScenarioBuilder fixedIterations = scenario("Fixed Iterations")
        .exec(
            // Initial session values: user-defined variables and JMeter properties used in requests
            exec(session -> session
                .set("threads", THREADS_2)),
            // Thread group loop count
            repeat(LOOPS).on(
                // GET /fixed (HTTPSamplerProxy)
                http("GET /fixed").get("/fixed"),
                exitHereIfFailed()
            )
        );

    // TestPlan > Forever Without Duration (ThreadGroup)
    // TODO(jmx2gatling) #1 Action after a sampler error is "stoptest"; Gatling does not stop the whole test on a failure. Consider stopLoadGenerator(...) or assertions [ThreadGroup]
    private final ScenarioBuilder foreverWithoutDuration = scenario("Forever Without Duration")
        .exec(
            // Initial session values: user-defined variables and JMeter properties used in requests
            exec(session -> session
                .set("threads", THREADS_2)),
            // TODO(jmx2gatling) #2 Thread group loops forever with no scheduler duration; using -DdurationSeconds (default 600 s) and a maxDuration on the simulation [ThreadGroup]
            during(Duration.ofSeconds(DURATION_SECONDS)).on(
                // GET /forever (HTTPSamplerProxy)
                http("GET /forever").get("/forever")
            )
        );

    // TestPlan > Unconvertible Numbers (ThreadGroup)
    // TODO(jmx2gatling) #3 Loop count `${__groovy(2 * 3)}` could not be converted; using 1 [ThreadGroup]
    // Original:
    //     ${__groovy(2 * 3)}
    private final ScenarioBuilder unconvertibleNumbers = scenario("Unconvertible Numbers")
        .exec(
            // Initial session values: user-defined variables and JMeter properties used in requests
            exec(session -> session
                .set("threads", THREADS_2)),
            // GET /odd (HTTPSamplerProxy)
            http("GET /odd").get("/odd")
        );

    {
        setUp(
            // Injection for TestPlan > Steady Load (ThreadGroup)
            steadyLoad.injectOpen(nothingFor(Duration.ofSeconds(10)), rampUsers(USERS).during(Duration.ofSeconds(RAMPUP)))
                .andThen(
                    // Injection for TestPlan > Fixed Iterations (ThreadGroup)
                    fixedIterations.injectOpen(rampUsers(USERS).during(Duration.ofSeconds(30)))
                        .andThen(
                            // Injection for TestPlan > Forever Without Duration (ThreadGroup)
                            foreverWithoutDuration.injectOpen(atOnceUsers(THREADS))
                                .andThen(
                                    // Injection for TestPlan > Unconvertible Numbers (ThreadGroup)
                                    // TODO(jmx2gatling) #4 Number of threads `${usersFromSomewhere}` could not be converted; using 1 [ThreadGroup]
                                    // Original:
                                    //     ${usersFromSomewhere}
                                    // TODO(jmx2gatling) #5 Ramp-up `${__P(ramp,fast)}` could not be converted; using 0 [ThreadGroup]
                                    // Original:
                                    //     ${__P(ramp,fast)}
                                    unconvertibleNumbers.injectOpen(atOnceUsers(1))
                                )
                        )
                )
        ).protocols(httpProtocol).maxDuration(Duration.ofSeconds(DURATION_SECONDS));
    }
}
