package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;
import java.util.regex.Pattern;

/**
 * Generated by jmx2gatling from 06-extractors-json-multivar.jmx.
 * Conversion notes: see conversion-report.md (5 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx06ExtractorsJsonMultivarSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://auth.example-extract.test");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Extract Things (ThreadGroup)
    private final ScenarioBuilder extractThings = scenario("Extract Things")
        .exec(
            // POST /oauth/token (HTTPSamplerProxy)
            // TODO(jmx2gatling) #1 Match number -1 for `all_scopes`: Gatling saves all matches as one list, while JMeter creates all_scopes_1..all_scopes_N and all_scopes_matchNr [JSONPostProcessor]
            http("POST /oauth/token").post("/oauth/token")
                .formParam("grant_type", "client_credentials")
                .check(jsonPath("$.access_token").find().withDefault("NO_TOKEN").saveAs("access_token"))
                .check(jsonPath("$.token_type").find().withDefault("Bearer").saveAs("token_type"))
                .check(jsonPath("$.scopes[*]").find(1).withDefault("").saveAs("second_scope"))
                .check(jsonPath("$.scopes[*]").findRandom().withDefault("").saveAs("random_scope"))
                .check(jsonPath("$.scopes[*]").findAll().optional().saveAs("all_scopes"))
                .check(jsonPath("$.items[?(@.price > 100)].sku").find().withDefault("NONE").saveAs("expensiveSku")),
            // GET /login-page (HTTPSamplerProxy)
            // TODO(jmx2gatling) #2 Match number -1 for `banner`: Gatling saves all matches as one list, while JMeter creates banner_1..banner_N and banner_matchNr [RegexExtractor]
            // TODO(jmx2gatling) #3 Regex template $2$-$1$ not supported (only $1$) [RegexExtractor]
            // Original:
            //     (\d+)-(\d+)
            // TODO(jmx2gatling) #4 Extracting from "true" is not supported (only the response body and URL) [RegexExtractor]
            // TODO(jmx2gatling) #5 XPathExtractor not supported [XPathExtractor]
            http("GET /login-page").get("/login-page")
                .header("Authorization", "#{token_type} #{access_token}")
                .check(regex("name=\"_csrf\" value=\"([^\"]+)\"").find().withDefault("CSRF_NOT_FOUND").saveAs("csrf"))
                .check(regex("href=\"(/help/[a-z]+)\"").find(1).optional().saveAs("secondLink"))
                .check(regex("data-banner=\"(\\w*)\"").findAll().optional().saveAs("banner"))
                .check(currentLocationRegex(";jsessionid=(\\w+)").find().optional().saveAs("jsessionid"))
                .check(regex("(?s)" + Pattern.quote("<span id=\"order-#{csrf}\">") + "(.*?)" + Pattern.quote("</span>")).find().withDefault("NO_ORDER").saveAs("orderNumber")),
            // POST /submit (HTTPSamplerProxy)
            http("POST /submit").post("/submit")
                .formParam("_csrf", "#{csrf}")
                .formParam("order", "#{orderNumber}")
                .formParam("trace", "#{traceIdFromScript}")
        );

    {
        setUp(
            // Injection for TestPlan > Extract Things (ThreadGroup)
            extractThings.injectOpen(atOnceUsers(1))
        ).protocols(httpProtocol);
    }
}
