package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 09-csv-feeders.jmx.
 * Conversion notes: see conversion-report.md (1 TODO).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx09CsvFeedersSimulation extends Simulation {

    // JMeter property addressFile; override with -DaddressFile=...
    private static final String ADDRESS_FILE = System.getProperty("addressFile", "addresses.csv");

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://feeds.example-csv.test");

    // TestPlan > Users (CSVDataSet)
    private final FeederBuilder<String> usersFeeder = csv("users.csv").circular();

    // TestPlan > Shoppers (ThreadGroup) > Products (CSVDataSet)
    // TODO(jmx2gatling) #1 The CSV file has no header row; Gatling needs one. Add this first line: sku,qty [CSVDataSet]
    private final FeederBuilder<String> productsFeeder = csv("products.csv").queue();

    // TestPlan > Shoppers (ThreadGroup) > Coupons (CSVDataSet)
    private final FeederBuilder<String> couponsFeeder = tsv("/data/feeds/coupons.tsv").circular();

    // TestPlan > Shoppers (ThreadGroup) > Exhausting List (CSVDataSet)
    private final FeederBuilder<String> exhaustingListFeeder = csv("one-pass.csv").queue();

    // TestPlan > Shoppers (ThreadGroup) > Shipping (GenericController) > Addresses (CSVDataSet)
    private final FeederBuilder<String> addressesFeeder = separatedValues(ADDRESS_FILE, ';').circular();

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Shoppers (ThreadGroup)
    private final ScenarioBuilder shoppers = scenario("Shoppers")
        .exec(
            // Thread group loop count
            repeat(5).on(
                // CSV Data Set: TestPlan > Users (CSVDataSet)
                feed(usersFeeder),
                // CSV Data Set: Products (CSVDataSet)
                feed(productsFeeder),
                // CSV Data Set: Coupons (CSVDataSet)
                feed(couponsFeeder),
                // CSV Data Set: Exhausting List (CSVDataSet)
                feed(exhaustingListFeeder),
                // CSV Data Set: Shipping (GenericController) > Addresses (CSVDataSet)
                feed(addressesFeeder),
                // GET /cart/add (HTTPSamplerProxy)
                http("GET /cart/add").get("/cart/add?sku=#{sku}&qty=#{qty}&user=#{username}"),
                // GET /coupon (HTTPSamplerProxy)
                http("GET /coupon").get("/coupon/#{coupon_code}/#{ticket}"),
                // Shipping (GenericController)
                // Shipping (GenericController) > GET /shipping/quote (HTTPSamplerProxy)
                http("GET /shipping/quote").get("/shipping/quote?street=#{street}&city=#{city}")
            )
        );

    // TestPlan > Admins (ThreadGroup)
    private final ScenarioBuilder admins = scenario("Admins")
        .exec(
            // CSV Data Set: TestPlan > Users (CSVDataSet)
            feed(usersFeeder),
            // GET /admin/users/{username} (HTTPSamplerProxy)
            http("GET /admin/users/{username}").get("/admin/users/#{username}")
        );

    {
        setUp(
            // Injection for TestPlan > Shoppers (ThreadGroup)
            shoppers.injectOpen(rampUsers(4).during(Duration.ofSeconds(2))),
            // Injection for TestPlan > Admins (ThreadGroup)
            admins.injectOpen(rampUsers(1).during(Duration.ofSeconds(1)))
        ).protocols(httpProtocol);
    }
}
