package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 07-assertions.jmx.
 * Conversion notes: see conversion-report.md (10 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx07AssertionsSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://verify.example-assert.test");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Assert Everything (ThreadGroup)
    private final ScenarioBuilder assertEverything = scenario("Assert Everything")
        .exec(
            // Initial session values: user-defined variables and JMeter properties used in requests
            exec(session -> session
                .set("userName", "assertion-user")),
            // GET /status-codes (HTTPSamplerProxy)
            http("GET /status-codes").get("/status-codes")
                .check(status().is(200))
                .check(status().in(200, 201))
                .check(status().not(500))
                .check(status().transform(code -> String.valueOf(code).matches("2\\d\\d")).is(true)),
            // GET /page-body (HTTPSamplerProxy)
            // TODO(jmx2gatling) #1 Or across patterns: Gatling checks are all required (AND) [ResponseAssertion]
            // Original:
            //     needle-one
            //     needle-two
            // TODO(jmx2gatling) #2 Applies to JMeter variable `someVar` instead of the response [ResponseAssertion]
            http("GET /page-body").get("/page-body")
                .check(substring("Welcome back, assertion-user"))
                .check(substring("StackTraceAssertMarker").notExists())
                .check(regex("order-\\d+"))
                .check(regex("\\A(?:\\{.*\\})\\z"))
                .check(substring("first-needle"))
                .check(substring("second-needle"))
                .check(substring("Hello #{userName}"))
                .check(substring("maintenance-page")),
            // GET /plain (HTTPSamplerProxy)
            // TODO(jmx2gatling) #3 Response Assertion on Assertion.response_message is not supported [ResponseAssertion]
            // Original:
            //     OK
            http("GET /plain").get("/plain")
                .check(bodyString().is("OK"))
                .check(bodyString().not("ERROR")),
            // GET /headers (HTTPSamplerProxy)
            // TODO(jmx2gatling) #4 Response header pattern does not map to a single header [ResponseAssertion]
            // Original:
            //     HTTP/1.1 200 OK
            http("GET /headers").get("/headers")
                .check(headerRegex("Content-Type", "\\Qapplication/json\\E").exists())
                .check(header("X-Debug").notExists())
                .check(header("Cache-Control").is("no-store")),
            // GET /api/order (HTTPSamplerProxy)
            // TODO(jmx2gatling) #5 JSON Assertion expecting null is not supported [JSONPathAssertion]
            // Original:
            //     $.discount
            http("GET /api/order").get("/api/order")
                .check(jsonPath("$.id").exists())
                .check(jsonPath("$.status").is("ok"))
                .check(jsonPath("$.status").transform(value -> value.matches("ok|accepted")).is(true))
                .check(jsonPath("$.status").not("error"))
                .check(jsonPath("$.version").is("1.5"))
                .check(jsonPath("$.warnings").notExists())
                .check(jsonPath("$.owner").isEL("#{userName}")),
            // GET /legacy-assertions (HTTPSamplerProxy)
            // TODO(jmx2gatling) #6 DurationAssertion not supported [DurationAssertion]
            // TODO(jmx2gatling) #7 SizeAssertion not supported [SizeAssertion]
            // TODO(jmx2gatling) #8 XPathAssertion not supported [XPathAssertion]
            // TODO(jmx2gatling) #9 Script not converted [JSR223Assertion]
            // Original:
            //     [language: groovy]
            //     if (!prev.getResponseDataAsString().contains("assert-script-marker")) {
            //           AssertionResult.setFailure(true)
            //       }
            // TODO(jmx2gatling) #10 Script not converted [BeanShellAssertion]
            // Original:
            //     Failure = !ResponseCode.equals("200");
            http("GET /legacy-assertions").get("/legacy-assertions")
        );

    {
        setUp(
            // Injection for TestPlan > Assert Everything (ThreadGroup)
            assertEverything.injectOpen(atOnceUsers(1))
        ).protocols(httpProtocol);
    }
}
