package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 13-unsupported-elements.jmx.
 * Conversion notes: see conversion-report.md (21 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx13UnsupportedElementsSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://app.example-unsupported.test");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Unsupported Things (ThreadGroup) > Interleave (InterleaveControl)
    private final ChainBuilder interleave = exec(
        // Interleave (InterleaveControl)
        // TODO(jmx2gatling) #17 InterleaveControl not converted; its children are converted inline as if in a Simple Controller [InterleaveControl]
        // Interleave (InterleaveControl) > GET /interleave/a (HTTPSamplerProxy)
        http("GET /interleave/a").get("/interleave/a"),
        // Interleave (InterleaveControl) > GET /interleave/b (HTTPSamplerProxy)
        http("GET /interleave/b").get("/interleave/b")
    );

    // TestPlan > Unsupported Things (ThreadGroup) > Run For 30s (RunTime)
    private final ChainBuilder runFor30s = exec(
        // Run For 30s (RunTime)
        // TODO(jmx2gatling) #18 RunTime not converted; its children are converted inline as if in a Simple Controller [RunTime]
        // Run For 30s (RunTime) > GET /runtime (HTTPSamplerProxy)
        http("GET /runtime").get("/runtime")
    );

    // TestPlan > Unsupported Things (ThreadGroup) > Include Shared Login (IncludeController)
    private final ChainBuilder includeSharedLogin = exec(
        // Include Shared Login (IncludeController)
        // TODO(jmx2gatling) #19 IncludeController not converted; convert the referenced test fragment and call it here [IncludeController]
        // Original:
        //     [include file: fragments/shared-login.jmx]
        exec(session -> session)
    );

    // TestPlan > Unsupported Things (ThreadGroup) > One At A Time (CriticalSectionController)
    private final ChainBuilder oneAtATime = exec(
        // One At A Time (CriticalSectionController)
        // TODO(jmx2gatling) #20 CriticalSectionController not converted; its children are converted inline as if in a Simple Controller [CriticalSectionController]
        // One At A Time (CriticalSectionController) > GET /critical (HTTPSamplerProxy)
        http("GET /critical").get("/critical")
    );

    // TestPlan > Unsupported Things (ThreadGroup)
    private final ScenarioBuilder unsupportedThings = scenario("Unsupported Things")
        .exec(
            // TODO(jmx2gatling) #1 KeystoreConfig not converted; it applied to every sampler in this scope [KeystoreConfig]
            // Timers: Before Script (ConstantTimer)
            pause(Duration.ofMillis(250)),
            // Groovy Setup Script (JSR223Sampler)
            // TODO(jmx2gatling) #2 Script sampler not converted; replaced by a no-op [JSR223Sampler]
            // Original:
            //     [language: groovy]
            //     import groovy.json.JsonSlurper
            //     /* a block comment that ends here */ def x = "\\u0041 is A"
            //     def unicodeLooking = "\\u0022 should stay text"
            //     vars.put("fromScript", new JsonSlurper().parseText(prev?.getResponseDataAsString() ?: "{}").id ?: "unsupported-script-value")
            exec(session -> session),
            // BeanShell Sampler (BeanShellSampler)
            // TODO(jmx2gatling) #3 Script sampler not converted; replaced by a no-op [BeanShellSampler]
            // Original:
            //     return "unsupported-beanshell-result";
            exec(session -> session),
            // Query Orders DB (JDBCSampler)
            // TODO(jmx2gatling) #4 Non-HTTP sampler JDBCSampler not converted; replaced by a no-op [JDBCSampler]
            exec(session -> session),
            // Raw TCP Ping (TCPSampler)
            // TODO(jmx2gatling) #5 Non-HTTP sampler TCPSampler not converted; replaced by a no-op [TCPSampler]
            exec(session -> session),
            // Publish To Queue (PublisherSampler)
            // TODO(jmx2gatling) #6 Non-HTTP sampler PublisherSampler not converted; replaced by a no-op [PublisherSampler]
            exec(session -> session),
            // Pause 1s (Flow Control) (TestAction)
            // TODO(jmx2gatling) #7 Non-HTTP sampler TestAction not converted; replaced by a no-op [TestAction]
            exec(session -> session),
            // Plugin Sampler (com.example.jmeter.FancySampler)
            // TODO(jmx2gatling) #8 Non-HTTP sampler com.example.jmeter.FancySampler not converted; replaced by a no-op [com.example.jmeter.FancySampler]
            exec(session -> session),
            // GET /target-of-unsupported (HTTPSamplerProxy)
            // TODO(jmx2gatling) #9 ConstantThroughputTimer not converted; the closest Gatling equivalent is throttle(...) on the setUp [ConstantThroughputTimer]
            // TODO(jmx2gatling) #10 PoissonRandomTimer not converted [PoissonRandomTimer]
            // TODO(jmx2gatling) #11 Script pre-processor not converted [BeanShellPreProcessor]
            // Original:
            //     vars.put("sig", "unsupported-bsh-signature");
            // TODO(jmx2gatling) #12 UserParameters not converted [UserParameters]
            http("GET /target-of-unsupported").get("/target"),
            // TODO(jmx2gatling) #13 AuthManager not converted; it applied to every sampler in this scope [AuthManager]
            // TODO(jmx2gatling) #14 DNSCacheManager not converted; it applied to every sampler in this scope [DNSCacheManager]
            // TODO(jmx2gatling) #15 CounterConfig not converted; it applied to every sampler in this scope [CounterConfig]
            // TODO(jmx2gatling) #16 RandomVariableConfig not converted; it applied to every sampler in this scope [RandomVariableConfig]
            // Interleave (InterleaveControl)
            interleave,
            // Run For 30s (RunTime)
            runFor30s,
            // Include Shared Login (IncludeController)
            includeSharedLogin,
            // One At A Time (CriticalSectionController)
            oneAtATime,
            // Weird | name <b>bold</b> \u00e9 */ end (HTTPSamplerProxy)
            http("Weird | name <b>bold</b> \u00e9 */ end").get("/weird")
        );

    // TestPlan > Ultimate Thread Group (kg.apc.jmeter.threads.UltimateThreadGroup)
    private final ScenarioBuilder ultimateThreadGroup = scenario("Ultimate Thread Group")
        .exec(
            // TODO(jmx2gatling) #1 KeystoreConfig not converted; it applied to every sampler in this scope [KeystoreConfig]
            // GET /ultimate (HTTPSamplerProxy)
            http("GET /ultimate").get("/ultimate")
        );

    {
        setUp(
            // Injection for TestPlan > Unsupported Things (ThreadGroup)
            unsupportedThings.injectOpen(atOnceUsers(1)),
            // Injection for TestPlan > Ultimate Thread Group (kg.apc.jmeter.threads.UltimateThreadGroup)
            // TODO(jmx2gatling) #21 kg.apc.jmeter.threads.UltimateThreadGroup load profile not converted; placeholder atOnceUsers(1). Write the injection profile by hand [kg.apc.jmeter.threads.UltimateThreadGroup]
            ultimateThreadGroup.injectOpen(atOnceUsers(1))
        ).protocols(httpProtocol);
    }
}
