package jmx2gatling.convert;

import java.util.ArrayList;
import java.util.List;

/** Writes a {@link SimulationModel} as Java source. Output depends only on the model, so it is deterministic. */
final class JavaWriter {

    private static final String INDENT = "    ";

    private final StringBuilder out = new StringBuilder();

    String write(SimulationModel m) {
        line(0, "package " + m.packageName() + ";");
        blank();
        line(0, "import static io.gatling.javaapi.core.CoreDsl.*;");
        line(0, "import static io.gatling.javaapi.http.HttpDsl.*;");
        blank();
        line(0, "import io.gatling.javaapi.core.*;");
        line(0, "import io.gatling.javaapi.http.*;");
        line(0, "import java.time.Duration;");
        if (m.usesPattern()) {
            line(0, "import java.util.regex.Pattern;");
        }
        blank();
        line(0, "/**");
        line(0, " * Generated by jmx2gatling from " + javadoc(m.sourceFileName())
            + (m.generatedOn() == null ? "." : " on " + m.generatedOn() + "."));
        line(0, " * Conversion notes: see conversion-report.md (" + m.todoCount() + " TODO" + (m.todoCount() == 1 ? "" : "s") + ").");
        line(0, " * Target: Gatling " + GatlingDsl.GATLING_VERSION + " Java DSL.");
        line(0, " */");
        line(0, "public class " + m.className() + " extends Simulation {");

        for (Constants.Constant constant : m.constants()) {
            blank();
            comments(1, List.of(constant.comment()));
            line(1, "private static final " + constant.type() + " " + constant.name() + " = " + constant.init() + ";");
        }
        for (SimulationModel.Field feeder : m.feeders()) {
            blank();
            comments(1, feeder.comments());
            line(1, "private final " + feeder.type() + " " + feeder.name() + " = " + feeder.expr() + ";");
        }

        blank();
        comments(1, m.protocolComments());
        line(1, "private final HttpProtocolBuilder httpProtocol = http");
        for (String call : m.protocolCalls()) {
            line(2, call);
        }
        line(2, ";");

        for (SimulationModel.ChainField chain : m.chains()) {
            blank();
            comments(1, chain.comments());
            line(1, "private final ChainBuilder " + chain.name() + " = exec(");
            steps(chain.steps(), 2);
            line(1, ");");
        }
        for (SimulationModel.ScenarioField scenario : m.scenarios()) {
            blank();
            comments(1, scenario.comments());
            line(1, "private final ScenarioBuilder " + scenario.name() + " = scenario(" + JavaText.quote(scenario.displayName()) + ")");
            line(2, ".exec(");
            steps(scenario.steps(), 3);
            line(2, ");");
        }

        blank();
        line(1, "{");
        line(2, "setUp(");
        populations(m.populations(), 3);
        line(2, ")" + GatlingDsl.protocols("httpProtocol") + (m.maxDuration() == null ? "" : m.maxDuration()) + ";");
        line(1, "}");

        for (Conversion.Helper helper : m.helpers()) {
            blank();
            helper(helper);
        }
        line(0, "}");
        return out.toString();
    }

    private void populations(List<SimulationModel.Population> populations, int depth) {
        for (int i = 0; i < populations.size(); i++) {
            SimulationModel.Population p = populations.get(i);
            comments(depth, p.comments());
            String comma = i < populations.size() - 1 ? "," : "";
            if (p.andThen().isEmpty()) {
                line(depth, p.expr() + comma);
            } else {
                line(depth, p.expr());
                line(depth + 1, ".andThen(");
                populations(p.andThen(), depth + 2);
                line(depth + 1, ")" + comma);
            }
        }
    }

    /** Writes steps as comma-separated chain elements; comment-only steps attach to the next element. */
    private void steps(List<Step> steps, int depth) {
        List<Step> real = new ArrayList<>();
        List<List<String>> realComments = new ArrayList<>();
        List<String> pending = new ArrayList<>();
        for (Step step : steps) {
            if (step instanceof Step.Note note) {
                pending.addAll(note.comments());
                continue;
            }
            List<String> comments = new ArrayList<>(pending);
            comments.addAll(step.comments());
            pending.clear();
            real.add(step);
            realComments.add(comments);
        }
        if (real.isEmpty()) {
            real.add(new Step.Action(List.of(), GatlingDsl.NO_OP));
            List<String> comments = new ArrayList<>(pending);
            comments.add("Nothing to run here");
            realComments.add(comments);
            pending.clear();
        }
        for (int i = 0; i < real.size(); i++) {
            comments(depth, realComments.get(i));
            step(real.get(i), depth, i < real.size() - 1 ? "," : "");
        }
        comments(depth, pending);
    }

    private void step(Step step, int depth, String suffix) {
        if (step instanceof Step.Action action) {
            multiline(depth, action.code(), suffix);
        } else if (step instanceof Step.Request request) {
            multiline(depth, request(request.spec(), depth), suffix);
        } else if (step instanceof Step.Block block) {
            line(depth, block.head() + "(");
            steps(block.body(), depth + 1);
            line(depth, ")" + suffix);
        } else if (step instanceof Step.Switch sw) {
            line(depth, sw.head() + "(");
            for (int i = 0; i < sw.branches().size(); i++) {
                branch(sw.branches().get(i), depth + 1, i < sw.branches().size() - 1 ? "," : "");
            }
            line(depth, ")" + suffix);
        }
    }

    private void branch(Step.Branch branch, int depth, String suffix) {
        long realSteps = branch.body().stream().filter(s -> !(s instanceof Step.Note)).count();
        if (branch.head() == null && realSteps == 1) {
            List<String> comments = new ArrayList<>();
            Step only = null;
            for (Step s : branch.body()) {
                comments.addAll(s.comments());
                if (!(s instanceof Step.Note)) {
                    only = s;
                    break;
                }
            }
            comments(depth, comments);
            step(only, depth, suffix);
            List<String> trailing = new ArrayList<>();
            boolean after = false;
            for (Step s : branch.body()) {
                if (after) {
                    trailing.addAll(s.comments());
                }
                after |= s == only;
            }
            comments(depth, trailing);
            return;
        }
        line(depth, (branch.head() == null ? "exec" : branch.head()) + "(");
        steps(branch.body(), depth + 1);
        line(depth, ")" + suffix);
    }

    private String request(RequestSpec r, int depth) {
        StringBuilder s = new StringBuilder(GatlingDsl.httpRequest(r.nameEl, r.method, r.url.javaExpr()));
        String continuation = "\n" + INDENT;
        for (RequestSpec.NameValue h : r.headers) {
            s.append(continuation).append(GatlingDsl.header(h.name(), h.valueEl()));
        }
        for (RequestSpec.NameValue q : r.queryParams) {
            s.append(continuation).append(GatlingDsl.queryParam(q.name(), q.valueEl()));
        }
        for (RequestSpec.NameValue f : r.formParams) {
            s.append(continuation).append(GatlingDsl.formParam(f.name(), f.valueEl()));
        }
        if (r.body instanceof RequestSpec.InlineBody inline) {
            String literal = inline.textEl().contains("\n") && JavaText.textBlockSafe(inline.textEl())
                ? JavaText.textBlock(inline.textEl(), INDENT.repeat(depth + 2))
                : JavaText.quote(inline.textEl());
            s.append(continuation).append(GatlingDsl.stringBody(literal));
        } else if (r.body instanceof RequestSpec.ElFile file) {
            s.append(continuation).append(GatlingDsl.elFileBody(file.resourcePath()));
        } else if (r.body instanceof RequestSpec.RawFile raw) {
            s.append(continuation).append(GatlingDsl.rawFileBody(raw.path()));
        }
        for (RequestSpec.FilePart part : r.fileParts) {
            s.append(continuation).append(GatlingDsl.rawFileBodyPart(part.partName(), part.path(), part.contentType(), part.fileName()));
        }
        if (r.multipart) {
            s.append(continuation).append(GatlingDsl.AS_MULTIPART_FORM);
        }
        if (r.disableFollowRedirect) {
            s.append(continuation).append(GatlingDsl.DISABLE_FOLLOW_REDIRECT);
        }
        for (String check : r.checks) {
            s.append(continuation).append(GatlingDsl.check(check));
        }
        return s.toString();
    }

    /**
     * Writes code whose later lines are already indented relative to its first line. Text-block
     * content lines carry their own absolute indentation and are written untouched.
     */
    private void multiline(int depth, String code, String suffix) {
        String[] lines = code.split("\n", -1);
        boolean inTextBlock = false;
        for (int i = 0; i < lines.length; i++) {
            String text = lines[i] + (i == lines.length - 1 ? suffix : "");
            if (inTextBlock) {
                out.append(text).append('\n');
            } else {
                line(depth, text);
            }
            if (countTextBlockDelimiters(lines[i]) % 2 == 1) {
                inTextBlock = !inTextBlock;
            }
        }
    }

    private static int countTextBlockDelimiters(String line) {
        int count = 0;
        int i = 0;
        while ((i = line.indexOf("\"\"\"", i)) >= 0) {
            if (i == 0 || line.charAt(i - 1) != '\\') {
                count++;
            }
            i += 3;
        }
        return count;
    }

    private void comments(int depth, List<String> comments) {
        for (String comment : comments) {
            line(depth, "// " + JavaText.comment(comment));
        }
    }

    private void helper(Conversion.Helper helper) {
        switch (helper) {
            case RANDOM_STRING -> {
                line(1, "/** Equivalent of JMeter's __RandomString: {@code length} characters picked from {@code chars}. */");
                line(1, "private static String randomString(int length, String chars) {");
                line(2, "java.util.concurrent.ThreadLocalRandom random = java.util.concurrent.ThreadLocalRandom.current();");
                line(2, "StringBuilder out = new StringBuilder(length);");
                line(2, "for (int i = 0; i < length; i++) {");
                line(3, "out.append(chars.charAt(random.nextInt(chars.length())));");
                line(2, "}");
                line(2, "return out.toString();");
                line(1, "}");
            }
            case COLLECT_SERIES -> {
                line(1, "/** The JMeter variable series prefix1, prefix2, ... as a list, the way a ForEach Controller reads it. */");
                line(1, "private static java.util.List<String> collectSeries(Session session, String prefix, int startExclusive, int endInclusive) {");
                line(2, "java.util.List<String> values = new java.util.ArrayList<>();");
                line(2, "for (int i = startExclusive + 1; endInclusive < 0 || i <= endInclusive; i++) {");
                line(3, "if (!session.contains(prefix + i)) {");
                line(4, "break;");
                line(3, "}");
                line(3, "values.add(session.getString(prefix + i));");
                line(2, "}");
                line(2, "return values;");
                line(1, "}");
            }
        }
    }

    private static String javadoc(String text) {
        return JavaText.comment(text).replace("*/", "* /");
    }

    private void line(int depth, String text) {
        out.append(INDENT.repeat(depth)).append(text).append('\n');
    }

    private void blank() {
        out.append('\n');
    }
}
