package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 16-no-thread-groups.jmx.
 * Conversion notes: see conversion-report.md (2 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx16NoThreadGroupsSimulation extends Simulation {

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    // TODO(jmx2gatling) #2 The plan has no enabled thread group, so the simulation injects no users [TestPlan]
    // TODO(jmx2gatling) #1 DNSCacheManager not converted; it applied to every sampler in this scope [DNSCacheManager]
    private final HttpProtocolBuilder httpProtocol = http
        .disableCaching()
        .disableWarmUp()
        ;

    {
        setUp(
        ).protocols(httpProtocol);
    }
}
