package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 12-bodies-raw-form-file.jmx.
 * Conversion notes: see conversion-report.md (3 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx12BodiesRawFormFileSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://bodies.example-bodies.test");

    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableWarmUp()
        ;

    // TestPlan > Body Senders (ThreadGroup)
    private final ScenarioBuilder bodySenders = scenario("Body Senders")
        .exec(
            // Initial session values: user-defined variables and JMeter properties used in requests
            exec(session -> session
                .set("user", "bodies-user")
                .set("symbol", "BDY")),
            // POST /notes (multi-line raw) (HTTPSamplerProxy)
            http("POST /notes (multi-line raw)").post("/notes")
                .body(StringBody("""
                    line one with "quotes" and a backslash \\ here
                    	indented with a tab
                    trailing spaces  \s
                    ""\"triple quotes""\"
                      \\#{literalEl} #{user}\
                    """)),
            // POST /soap/quote (HTTPSamplerProxy)
            http("POST /soap/quote").post("/soap/quote")
                .body(ElFileBody("bodies/jmx12-bodies-raw-form-file/post-soap-quote.xml")),
            // PUT /profile (form) (HTTPSamplerProxy)
            http("PUT /profile (form)").put("/profile")
                .formParam("displayName", "Bodies #{user}")
                .formParam("bio", "likes & tests"),
            // PATCH /profile (raw json) (HTTPSamplerProxy)
            http("PATCH /profile (raw json)").patch("/profile")
                .body(StringBody("{\"theme\":\"dark\"}")),
            // POST /documents (multipart) (HTTPSamplerProxy)
            http("POST /documents (multipart)").post("/documents")
                .formParam("title", "Quarterly report")
                .bodyPart(RawFileBodyPart("document", "/uploads/bodies-report.pdf").contentType("application/pdf").fileName("bodies-report.pdf"))
                .asMultipartForm(),
            // POST /import (file as body) (HTTPSamplerProxy)
            http("POST /import (file as body)").post("/import")
                .header("Content-Type", "application/octet-stream")
                .body(RawFileBody("data/bodies-import.bin")),
            // POST /legacy (unnamed arguments) (HTTPSamplerProxy)
            http("POST /legacy (unnamed arguments)").post("/legacy")
                .body(StringBody("a=1&b=2")),
            // GET /redirect-me (no follow) (HTTPSamplerProxy)
            http("GET /redirect-me (no follow)").get("/redirect-me")
                .disableFollowRedirect(),
            // GET /page-with-assets (HTTPSamplerProxy)
            // TODO(jmx2gatling) #1 "Retrieve all embedded resources" is on; Gatling does not fetch them unless you add http.inferHtmlResources() to the protocol or list them with .resources(...) [HTTPSamplerProxy]
            http("GET /page-with-assets").get("/page-with-assets"),
            // GET /slow (HTTPSamplerProxy)
            http("GET /slow").get("/slow"),
            // DELETE /notes/1 (with body) (HTTPSamplerProxy)
            http("DELETE /notes/1 (with body)").delete("/notes/1")
                .body(StringBody("{\"reason\":\"cleanup\"}")),
            // OPTIONS /notes (HTTPSamplerProxy)
            http("OPTIONS /notes").options("/notes"),
            // HEAD /notes (HTTPSamplerProxy)
            http("HEAD /notes").head("/notes"),
            // PROPFIND /dav (HTTPSamplerProxy)
            http("PROPFIND /dav").httpRequest("PROPFIND", "/dav"),
            // GET with body (HTTPSamplerProxy)
            // TODO(jmx2gatling) #2 Request body on a GET request is not sent by Gatling's GET DSL [HTTPSamplerProxy]
            // Original:
            //     {"q":"get-with-body"}
            http("GET with body").get("/search"),
            // POST mixed upload (HTTPSamplerProxy)
            // TODO(jmx2gatling) #3 File upload mixing a raw file body with parameters [HTTPSamplerProxy]
            http("POST mixed upload").post("/mixed")
                .formParam("note", "x"),
            // GET /query-in-path (HTTPSamplerProxy)
            http("GET /query-in-path").get("/search?q=already&page=2")
        );

    {
        setUp(
            // Injection for TestPlan > Body Senders (ThreadGroup)
            bodySenders.injectOpen(atOnceUsers(1))
        ).protocols(httpProtocol);
    }
}
