package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 14-mixed-hosts.jmx.
 * Conversion notes: see conversion-report.md (0 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx14MixedHostsSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://api.example-hosts.test");

    // Another host the plan calls; override with -DbaseUrl2=...
    private static final String BASE_URL_2 = System.getProperty("baseUrl2", "https://auth.example-hosts.test");

    // Another host the plan calls; override with -DbaseUrl3=...
    private static final String BASE_URL_3 = System.getProperty("baseUrl3", "http://api.example-hosts.test:8080");

    // Another host the plan calls; override with -DbaseUrl4=...
    private static final String BASE_URL_4 = System.getProperty("baseUrl4", "https://cdn.example-hosts.test");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .header("Accept", "application/json")
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Host Hopper (ThreadGroup)
    private final ScenarioBuilder hostHopper = scenario("Host Hopper")
        .exec(
            // POST /login (auth host) (HTTPSamplerProxy)
            http("POST /login (auth host)").post(BASE_URL_2 + "/login")
                .check(jsonPath("$.tenant.host").find().withDefault("tenant.example-hosts.test").saveAs("tenantHost")),
            // GET /api/a (HTTPSamplerProxy)
            http("GET /api/a").get("/api/a"),
            // GET /api/b (HTTPSamplerProxy)
            http("GET /api/b").get("/api/b"),
            // GET /api/c (HTTPSamplerProxy)
            http("GET /api/c").get("/api/c"),
            // GET /api/legacy (port 8080) (HTTPSamplerProxy)
            http("GET /api/legacy (port 8080)").get(BASE_URL_3 + "/api/legacy"),
            // GET asset (absolute URL in path) (HTTPSamplerProxy)
            http("GET asset (absolute URL in path)").get(BASE_URL_4 + "/static/app.js"),
            // GET tenant home (runtime host) (HTTPSamplerProxy)
            http("GET tenant home (runtime host)").get("https://#{tenantHost}/home"),
            // GET /api/d (port 443 implies https) (HTTPSamplerProxy)
            http("GET /api/d (port 443 implies https)").get("/api/d")
        );

    {
        setUp(
            // Injection for TestPlan > Host Hopper (ThreadGroup)
            hostHopper.injectOpen(atOnceUsers(1))
        ).protocols(httpProtocol);
    }
}
