package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 05-controllers-all.jmx.
 * Conversion notes: see conversion-report.md (6 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx05ControllersAllSimulation extends Simulation {

    // JMeter property pages; override with -Dpages=...
    private static final int PAGES = Integer.getInteger("pages", 3);

    // JMeter property heartbeatMillis; override with -DheartbeatMillis=...
    private static final int HEARTBEAT_MILLIS = Integer.getInteger("heartbeatMillis", 5000);

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://tour.example-controllers.test");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Controller Tour (ThreadGroup) > If Logged In (IfController)
    private final ChainBuilder ifLoggedIn = exec(
        // If Logged In (IfController)
        doIf(session -> "true".equals(session.getString("loggedIn"))).then(
            // If Logged In (IfController) > GET /dashboard (HTTPSamplerProxy)
            http("GET /dashboard").get("/dashboard")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > If Not Admin (JavaScript) (IfController)
    private final ChainBuilder ifNotAdminJavaScript = exec(
        // If Not Admin (JavaScript) (IfController)
        doIf(session -> !"admin".equals(session.getString("role"))).then(
            // If Not Admin (JavaScript) (IfController) > GET /upgrade-offer (HTTPSamplerProxy)
            http("GET /upgrade-offer").get("/upgrade-offer")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > If Member Flag (IfController)
    private final ChainBuilder ifMemberFlag = exec(
        // If Member Flag (IfController)
        doIf(session -> "true".equalsIgnoreCase(session.getString("isMember"))).then(
            // If Member Flag (IfController) > GET /member-perks (HTTPSamplerProxy)
            http("GET /member-perks").get("/member-perks")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > If Many Orders (complex) (IfController)
    private final ChainBuilder ifManyOrdersComplex = exec(
        // If Many Orders (complex) (IfController)
        // TODO(jmx2gatling) #2 Condition not converted; placeholder is session -> true [IfController]
        // Original:
        //     ${__groovy(vars.getObject("ids")?.size() > 5 && vars.get("role") != "guest")}
        doIf(session -> true).then(
            // If Many Orders (complex) (IfController) > GET /loyalty (HTTPSamplerProxy)
            http("GET /loyalty").get("/loyalty")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > If Last Sample OK (IfController)
    private final ChainBuilder ifLastSampleOK = exec(
        // If Last Sample OK (IfController)
        doIf(session -> !session.isFailed()).then(
            // If Last Sample OK (IfController) > GET /next-step (HTTPSamplerProxy)
            http("GET /next-step").get("/next-step")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > Poll Until Done (WhileController)
    private final ChainBuilder pollUntilDone = exec(
        // Poll Until Done (WhileController)
        asLongAs(session -> !"DONE".equals(session.getString("jobStatus"))).on(
            // Poll Until Done (WhileController) > GET /job/status (HTTPSamplerProxy)
            http("GET /job/status").get("/job/status")
                .check(jsonPath("$.status").findRandom().withDefault("DONE").saveAs("jobStatus"))
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > Retry While Failing (WhileController)
    private final ChainBuilder retryWhileFailing = exec(
        // Retry While Failing (WhileController)
        // TODO(jmx2gatling) #3 Empty condition (loop until a sampler in the loop fails) not converted; placeholder is session -> true [WhileController]
        asLongAs(session -> true).on(
            // Retry While Failing (WhileController) > POST /flaky (HTTPSamplerProxy)
            http("POST /flaky").post("/flaky")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > Pages From Property (LoopController)
    private final ChainBuilder pagesFromProperty = exec(
        // Pages From Property (LoopController)
        repeat(PAGES).on(
            // Pages From Property (LoopController) > GET /catalog/page (HTTPSamplerProxy)
            http("GET /catalog/page").get("/catalog/page")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > Pages From Response (LoopController)
    private final ChainBuilder pagesFromResponse = exec(
        // Pages From Response (LoopController)
        repeat("#{pageCount}").on(
            // Pages From Response (LoopController) > GET /history/page (HTTPSamplerProxy)
            http("GET /history/page").get("/history/page")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > Each Order Id (ForeachController)
    private final ChainBuilder eachOrderId = exec(
        // Each Order Id (ForeachController)
        foreach("#{ids}", "orderId").on(
            // Each Order Id (ForeachController) > GET /orders/{id} (HTTPSamplerProxy)
            http("GET /orders/{id}").get("/orders/#{orderId}")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > Each Coupon Variable (ForeachController)
    private final ChainBuilder eachCouponVariable = exec(
        // Collect coupon_1..coupon_N into a list for foreach
        exec(session -> session.set("jmx2g_series_1", collectSeries(session, "coupon_", 0, 3))),
        // Each Coupon Variable (ForeachController)
        foreach("#{jmx2g_series_1}", "couponCode").on(
            // Each Coupon Variable (ForeachController) > POST /coupons/apply (HTTPSamplerProxy)
            http("POST /coupons/apply").post("/coupons/apply")
                .formParam("code", "#{couponCode}")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > Quarter Of Users Review (ThroughputController)
    private final ChainBuilder quarterOfUsersReview = exec(
        // Quarter Of Users Review (ThroughputController)
        randomSwitch().on(
            percent(25.0).then(
                // Quarter Of Users Review (ThroughputController) > POST /reviews (HTTPSamplerProxy)
                http("POST /reviews").post("/reviews")
            )
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > Five Exports Per User (ThroughputController)
    private final ChainBuilder fiveExportsPerUser = exec(
        // Five Exports Per User (ThroughputController)
        // TODO(jmx2gatling) #4 Total Executions mode (5 executions per user) not converted; children always run [ThroughputController]
        // Five Exports Per User (ThroughputController) > GET /export (HTTPSamplerProxy)
        http("GET /export").get("/export")
    );

    // TestPlan > Controller Tour (ThreadGroup) > Random Footer Link (RandomController)
    private final ChainBuilder randomFooterLink = exec(
        // Random Footer Link (RandomController)
        uniformRandomSwitch().on(
            // Random Footer Link (RandomController) > GET /about (HTTPSamplerProxy)
            http("GET /about").get("/about"),
            // Random Footer Link (RandomController) > GET /careers (HTTPSamplerProxy)
            http("GET /careers").get("/careers")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup) > Switch By Role (SwitchController)
    private final ChainBuilder switchByRole = exec(
        // Switch By Role (SwitchController)
        // TODO(jmx2gatling) #5 SwitchController not converted; its children are converted inline as if in a Simple Controller [SwitchController]
        // Switch By Role (SwitchController) > guest (HTTPSamplerProxy)
        http("guest").get("/welcome/guest"),
        // Switch By Role (SwitchController) > member (HTTPSamplerProxy)
        http("member").get("/welcome/member")
    );

    // TestPlan > Controller Tour (ThreadGroup) > Reuse Login Module (ModuleController)
    private final ChainBuilder reuseLoginModule = exec(
        // Reuse Login Module (ModuleController)
        // TODO(jmx2gatling) #6 ModuleController not converted; convert the referenced test fragment and call it here [ModuleController]
        // Original:
        //     [module: Test Plan > Login Fragment]
        exec(session -> session)
    );

    // TestPlan > Controller Tour (ThreadGroup) > Heartbeat Forever (LoopController)
    private final ChainBuilder heartbeatForever = exec(
        // Heartbeat Forever (LoopController)
        forever().on(
            // Timers: Heartbeat Interval (ConstantTimer)
            pause(Duration.ofMillis(HEARTBEAT_MILLIS)),
            // Heartbeat Forever (LoopController) > GET /heartbeat (HTTPSamplerProxy)
            http("GET /heartbeat").get("/heartbeat")
        )
    );

    // TestPlan > Controller Tour (ThreadGroup)
    private final ScenarioBuilder controllerTour = scenario("Controller Tour")
        .exec(
            // GET /profile (HTTPSamplerProxy)
            // TODO(jmx2gatling) #1 Match number -1 for `ids`: Gatling saves all matches as one list, while JMeter creates ids_1..ids_N and ids_matchNr [JSONPostProcessor]
            http("GET /profile").get("/profile")
                .check(jsonPath("$.loggedIn").find().withDefault("false").saveAs("loggedIn"))
                .check(jsonPath("$.role").find().withDefault("guest").saveAs("role"))
                .check(jsonPath("$.member").find().withDefault("false").saveAs("isMember"))
                .check(jsonPath("$.orders[*].id").findAll().optional().saveAs("ids"))
                .check(jsonPath("$.pages").find().withDefault("0").saveAs("pageCount")),
            // If Logged In (IfController)
            ifLoggedIn,
            // If Not Admin (JavaScript) (IfController)
            ifNotAdminJavaScript,
            // If Member Flag (IfController)
            ifMemberFlag,
            // If Many Orders (complex) (IfController)
            ifManyOrdersComplex,
            // If Last Sample OK (IfController)
            ifLastSampleOK,
            // Poll Until Done (WhileController)
            pollUntilDone,
            // Retry While Failing (WhileController)
            retryWhileFailing,
            // Pages From Property (LoopController)
            pagesFromProperty,
            // Pages From Response (LoopController)
            pagesFromResponse,
            // Each Order Id (ForeachController)
            eachOrderId,
            // Each Coupon Variable (ForeachController)
            eachCouponVariable,
            // Quarter Of Users Review (ThroughputController)
            quarterOfUsersReview,
            // Five Exports Per User (ThroughputController)
            fiveExportsPerUser,
            // Random Footer Link (RandomController)
            randomFooterLink,
            // Switch By Role (SwitchController)
            switchByRole,
            // Reuse Login Module (ModuleController)
            reuseLoginModule,
            // Heartbeat Forever (LoopController)
            heartbeatForever
        );

    {
        setUp(
            // Injection for TestPlan > Controller Tour (ThreadGroup)
            controllerTour.injectOpen(rampUsers(1).during(Duration.ofSeconds(1)))
        ).protocols(httpProtocol);
    }

    /** The JMeter variable series prefix1, prefix2, ... as a list, the way a ForEach Controller reads it. */
    private static java.util.List<String> collectSeries(Session session, String prefix, int startExclusive, int endInclusive) {
        java.util.List<String> values = new java.util.ArrayList<>();
        for (int i = startExclusive + 1; endInclusive < 0 || i <= endInclusive; i++) {
            if (!session.contains(prefix + i)) {
                break;
            }
            values.add(session.getString(prefix + i));
        }
        return values;
    }
}
