package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 01-basic-get-post.jmx.
 * Conversion notes: see conversion-report.md (0 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx01BasicGetPostSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://shop.example-basic.test");

    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .header("Accept", "application/json")
        .header("User-Agent", "fixture-agent/1.0")
        .disableWarmUp()
        ;

    // TestPlan > Browse and Order (ThreadGroup)
    private final ScenarioBuilder browseAndOrder = scenario("Browse and Order")
        .exec(
            // Initial session values: user-defined variables and JMeter properties used in requests
            exec(session -> session
                .set("api_version", "v2")
                .set("search_term", "ultralight-laptops")),
            // Thread group loop count
            repeat(3).on(
                // GET /api/products (HTTPSamplerProxy)
                http("GET /api/products").get("/api/#{api_version}/products")
                    .queryParam("q", "#{search_term}")
                    .queryParam("page", "1"),
                // POST /login (HTTPSamplerProxy)
                http("POST /login").post("/login")
                    .formParam("username", "fixture-user-basic")
                    .formParam("password", "s3cret-basic-pass")
                    .check(status().is(200)),
                // POST /api/cart (HTTPSamplerProxy)
                http("POST /api/cart").post("/api/cart")
                    .header("Content-Type", "application/json")
                    .body(StringBody("{\"sku\": \"SKU-BASIC-1001\", \"qty\": 1}")),
                // POST /api/orders (HTTPSamplerProxy)
                http("POST /api/orders").post("/api/orders")
                    .header("Content-Type", "application/json")
                    .body(ElFileBody("bodies/jmx01-basic-get-post/post-api-orders.json"))
            )
        );

    {
        setUp(
            // Injection for TestPlan > Browse and Order (ThreadGroup)
            browseAndOrder.injectOpen(rampUsers(5).during(Duration.ofSeconds(10)))
        ).protocols(httpProtocol);
    }
}
