package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 02-nested-controllers.jmx.
 * Conversion notes: see conversion-report.md (0 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx02NestedControllersSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://checkout.example-nested.test:8443");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Checkout Flow (ThreadGroup) > Login Once (OnceOnlyController)
    private final ChainBuilder loginOnce = exec(
        // Login Once (OnceOnlyController)
        doIf(session -> !session.contains("jmx2g_once_1")).then(
            exec(session -> session.set("jmx2g_once_1", true)),
            // Login Once (OnceOnlyController) > POST /session (HTTPSamplerProxy)
            http("POST /session").post("/session")
                .formParam("user", "nested-shopper")
        )
    );

    // TestPlan > Checkout Flow (ThreadGroup) > Browse Catalog (TransactionController)
    private final ChainBuilder browseCatalog = exec(
        // Browse Catalog (TransactionController)
        group("Browse Catalog").on(
            // Browse Catalog (TransactionController) > GET /catalog (HTTPSamplerProxy)
            http("GET /catalog").get("/catalog"),
            // Browse Catalog (TransactionController) > View Three Items (LoopController)
            repeat(3).on(
                // Browse Catalog (TransactionController) > View Three Items (LoopController) > Item Steps (GenericController)
                // Browse Catalog (TransactionController) > View Three Items (LoopController) > Item Steps (GenericController) > GET /catalog/item (HTTPSamplerProxy)
                http("GET /catalog/item").get("/catalog/item"),
                // Browse Catalog (TransactionController) > View Three Items (LoopController) > Item Steps (GenericController) > Show Banner Once (OnceOnlyController)
                doIf(session -> !session.contains("jmx2g_once_2")).then(
                    exec(session -> session.set("jmx2g_once_2", true)),
                    // Browse Catalog (TransactionController) > View Three Items (LoopController) > Item Steps (GenericController) > Show Banner Once (OnceOnlyController) > GET /banner (HTTPSamplerProxy)
                    http("GET /banner").get("/banner")
                )
            )
        )
    );

    // TestPlan > Checkout Flow (ThreadGroup) > Pick Recommendation (TransactionController)
    private final ChainBuilder pickRecommendation = exec(
        // Pick Recommendation (TransactionController)
        group("Pick Recommendation").on(
            // Pick Recommendation (TransactionController) > One Of (RandomController)
            uniformRandomSwitch().on(
                // Pick Recommendation (TransactionController) > One Of (RandomController) > GET /recommend/popular (HTTPSamplerProxy)
                http("GET /recommend/popular").get("/recommend/popular"),
                exec(
                    // Pick Recommendation (TransactionController) > One Of (RandomController) > New Arrivals (GenericController)
                    // Pick Recommendation (TransactionController) > One Of (RandomController) > New Arrivals (GenericController) > GET /recommend/new (HTTPSamplerProxy)
                    http("GET /recommend/new").get("/recommend/new"),
                    // Pick Recommendation (TransactionController) > One Of (RandomController) > New Arrivals (GenericController) > GET /recommend/new/details (HTTPSamplerProxy)
                    http("GET /recommend/new/details").get("/recommend/new/details")
                )
            )
        )
    );

    // TestPlan > Checkout Flow (ThreadGroup)
    private final ScenarioBuilder checkoutFlow = scenario("Checkout Flow")
        .exec(
            // Thread group loop count
            repeat(2).on(
                // Cookies are cleared at each iteration, as in JMeter
                exec(flushCookieJar()),
                // Login Once (OnceOnlyController)
                loginOnce,
                // Browse Catalog (TransactionController)
                browseCatalog,
                // Pick Recommendation (TransactionController)
                pickRecommendation,
                // DELETE /session (HTTPSamplerProxy)
                http("DELETE /session").delete("/session")
            )
        );

    {
        setUp(
            // Injection for TestPlan > Checkout Flow (ThreadGroup)
            checkoutFlow.injectOpen(atOnceUsers(10))
        ).protocols(httpProtocol);
    }
}
