package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 08-functions-variables.jmx.
 * Conversion notes: see conversion-report.md (5 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx08FunctionsVariablesSimulation extends Simulation {

    // Global counter for ${__counter(FALSE,globalCount)}
    private static final java.util.concurrent.atomic.AtomicLong COUNTER = new java.util.concurrent.atomic.AtomicLong();

    // JMeter property apiVersion; override with -DapiVersion=...
    private static final String API_VERSION = System.getProperty("apiVersion", "v1");

    // JMeter property region; override with -Dregion=...
    private static final String REGION = System.getProperty("region", "eu-west-functions");

    // JMeter property pageSize; override with -DpageSize=...
    private static final String PAGE_SIZE = System.getProperty("pageSize", "1");

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://fn.example-functions.test");

    // JMeter property greeting; override with -Dgreeting=...
    private static final String GREETING = System.getProperty("greeting", "hello");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Function Users (ThreadGroup)
    private final ScenarioBuilder functionUsers = scenario("Function Users")
        .exec(
            // Initial session values: user-defined variables and JMeter properties used in requests
            // TODO(jmx2gatling) #5 User-defined variable `startedAt` uses functions or runtime variables; kept as literal text [TestPlan]
            // Original:
            //     ${__time()}
            exec(session -> session
                .set("base_path", "/api")
                .set("host", "fn.example-functions.test")
                .set("api_key", "key-value-functions")
                .set("greeting", GREETING + " from fn.example-functions.test")
                .set("startedAt", "${__time()}")
                .set("channel", "web-functions")
                .set("jmx2g_API_VERSION", API_VERSION)
                .set("jmx2g_PAGE_SIZE", PAGE_SIZE)
                .set("jmx2g_REGION", REGION)),
            // Thread group loop count
            repeat(2).on(
                // GET ids (HTTPSamplerProxy)
                http("GET ids").get("#{base_path}/ids")
                    .header("X-Correlation-Id", "#{randomUuid()}")
                    .header("X-Channel", "#{channel}")
                    .queryParam("uuid", "#{randomUuid()}")
                    .queryParam("uuidNoParens", "#{randomUuid()}")
                    .queryParam("thread", "#{userId()}")
                    .queryParam("key", "#{api_key}")
                    .queryParam("greeting", "#{greeting}"),
                // __time for the request below
                exec(session -> session.set("jmx2g_fn_1", new java.text.SimpleDateFormat("YYYY-'W'ww").format(new java.util.Date()))),
                // __time for the request below
                exec(session -> session.set("jmx2g_fn_2", String.valueOf(System.currentTimeMillis() / 1000L))),
                // __time for the request below
                exec(session -> session.set("todayVar", new java.text.SimpleDateFormat("yyyyMMdd").format(new java.util.Date()))),
                // __time for the request below
                exec(session -> session.set("jmx2g_fn_3", new java.text.SimpleDateFormat("EEE, d MMM yyyy").format(new java.util.Date()))),
                // GET time (HTTPSamplerProxy)
                http("GET time").get("/time")
                    .queryParam("millis", "#{currentTimeMillis()}")
                    .queryParam("iso", "#{currentDate(yyyy-MM-dd'T'HH:mm:ss.SSS)}")
                    .queryParam("week", "#{jmx2g_fn_1}")
                    .queryParam("seconds", "#{jmx2g_fn_2}")
                    .queryParam("today", "#{todayVar}")
                    .queryParam("longDate", "#{jmx2g_fn_3}"),
                // __Random for the request below
                exec(session -> session.set("lastRandom", String.valueOf(java.util.concurrent.ThreadLocalRandom.current().nextLong(100L, 999L + 1)))),
                // __RandomString for the request below
                exec(session -> session.set("jmx2g_fn_4", randomString(8, "abcdef0123"))),
                // __RandomString for the request below
                exec(session -> session.set("jmx2g_fn_5", randomString(12, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"))),
                // GET random (HTTPSamplerProxy)
                // TODO(jmx2gatling) #1 __RandomString with non-literal arguments [HTTPSamplerProxy]
                // Original:
                //     ${__RandomString(${len},abc)}
                http("GET random").get("/random/#{randomInt(1,11)}")
                    .queryParam("stored", "#{lastRandom}")
                    .queryParam("big", "#{randomLong(1,10000000000)}")
                    .queryParam("token", "#{jmx2g_fn_4}")
                    .queryParam("anyChars", "#{jmx2g_fn_5}")
                    .queryParam("dynamicLength", "${__RandomString(${len},abc)}"),
                // ${__counter(TRUE,)} for the request below
                exec(session -> {
                    long next = session.contains("jmx2g_counter_6") ? session.getLong("jmx2g_counter_6") + 1 : 1;
                    return session.set("jmx2g_counter_6", next).set("jmx2g_counter_6_value", String.valueOf(next));
                }),
                // ${__counter(FALSE,globalCount)} for the request below
                exec(session -> session.set("globalCount", String.valueOf(COUNTER.incrementAndGet()))),
                // GET counters (HTTPSamplerProxy)
                http("GET counters").get("/counters")
                    .queryParam("mine", "#{jmx2g_counter_6_value}")
                    .queryParam("global", "#{globalCount}"),
                // GET properties (HTTPSamplerProxy)
                http("GET properties").get("/#{jmx2g_API_VERSION}/items")
                    .queryParam("region", "#{jmx2g_REGION}")
                    .queryParam("defaultOne", "#{jmx2g_PAGE_SIZE}"),
                // GET unsupported functions (HTTPSamplerProxy)
                // TODO(jmx2gatling) #2 Script function __groovy not converted; kept verbatim [HTTPSamplerProxy]
                // Original:
                //     ${__groovy(new Date().format('yyyy'),)}
                // TODO(jmx2gatling) #3 Function __urlencode not supported; kept verbatim [HTTPSamplerProxy]
                // Original:
                //     ${__urlencode(fn value with spaces)}
                // TODO(jmx2gatling) #4 JMeter built-in variable ${__jm__Function Users__idx} has no direct Gatling equivalent; kept verbatim [HTTPSamplerProxy]
                // Original:
                //     ${__jm__Function Users__idx}
                http("GET unsupported functions").get("/unsupported")
                    .queryParam("year", "${__groovy(new Date().format('yyyy'),)}")
                    .queryParam("encoded", "${__urlencode(fn value with spaces)}")
                    .queryParam("loopIndex", "${__jm__Function Users__idx}"),
                // POST literal markers (HTTPSamplerProxy)
                http("POST literal markers").post("/literal")
                    .body(StringBody("{\"template\": \"\\#{notGatlingEl}\", \"price\": \"${notAJmeterVar}\", \"key\": \"#{api_key}\", \"path\": \"C:\\\\temp\\\\x\"}"))
            )
        );

    {
        setUp(
            // Injection for TestPlan > Function Users (ThreadGroup)
            functionUsers.injectOpen(rampUsers(2).during(Duration.ofSeconds(2)))
        ).protocols(httpProtocol);
    }

    /** Equivalent of JMeter's __RandomString: {@code length} characters picked from {@code chars}. */
    private static String randomString(int length, String chars) {
        java.util.concurrent.ThreadLocalRandom random = java.util.concurrent.ThreadLocalRandom.current();
        StringBuilder out = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            out.append(chars.charAt(random.nextInt(chars.length())));
        }
        return out.toString();
    }
}
