package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 04-scoped-headers-assertions-timers.jmx.
 * Conversion notes: see conversion-report.md (2 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx04ScopedHeadersAssertionsTimersSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://portal.example-scope.test");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .header("X-Plan", "plan-level-scope")
        .header("accept", "application/json")
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Scoped Users (ThreadGroup) > Account (TransactionController)
    private final ChainBuilder account = exec(
        // Account (TransactionController)
        group("Account").on(
            // Timers: Plan Think Time (ConstantTimer), Thread Group Random Pause (UniformRandomTimer), Account Gaussian Pause (GaussianRandomTimer)
            pause(Duration.ofMillis(700), Duration.ofMillis(1200)),
            // Account (TransactionController) > GET /account (HTTPSamplerProxy)
            // TODO(jmx2gatling) #1 Script pre-processor not converted [JSR223PreProcessor]
            // Original:
            //     [language: groovy]
            //     def nonce = UUID.randomUUID().toString()
            //     vars.put("nonce", nonce) /* scope-fixture-script */
            //     sampler.getHeaderManager()?.add(new org.apache.jmeter.protocol.http.control.Header("X-Nonce", nonce))
            // TODO(jmx2gatling) #2 Script not converted [JSR223PostProcessor]
            // Original:
            //     [language: groovy]
            //     vars.put("accountId", prev.getResponseHeaders().find(/X-Account: (\d+)/) { m, id -> id })
            http("GET /account").get("/account")
                .header("X-Team", "account-team")
                .header("X-Section", "account")
                .queryParam("locale", "en-US")
                .check(status().is(200)),
            // Timers: Plan Think Time (ConstantTimer), Thread Group Random Pause (UniformRandomTimer), Account Gaussian Pause (GaussianRandomTimer), Settings Extra Pause (ConstantTimer)
            pause(Duration.ofMillis(750), Duration.ofMillis(1250)),
            // Account (TransactionController) > GET /account/settings (HTTPSamplerProxy)
            // TODO(jmx2gatling) #1 Script pre-processor not converted [JSR223PreProcessor]
            // (original shown at the first #1 marker and in conversion-report.md)
            // TODO(jmx2gatling) #2 Script not converted [JSR223PostProcessor]
            // (original shown at the first #2 marker and in conversion-report.md)
            http("GET /account/settings").get("/account/settings")
                .header("X-Team", "account-team")
                .header("X-Section", "settings")
                .queryParam("locale", "de-DE")
                .check(status().is(200))
                .check(substring("notification-preferences"))
        )
    );

    // TestPlan > Scoped Users (ThreadGroup)
    private final ScenarioBuilder scopedUsers = scenario("Scoped Users")
        .exec(
            // User-defined cookie from TestPlan > Scoped Users (ThreadGroup) > HTTP Cookie Manager (CookieManager)
            exec(addCookie(Cookie("consent", "accepted-scope").withDomain("portal.example-scope.test").withPath("/"))),
            // Account (TransactionController)
            account,
            // Timers: Plan Think Time (ConstantTimer), Thread Group Random Pause (UniformRandomTimer)
            pause(Duration.ofMillis(300), Duration.ofMillis(600)),
            // GET /home (HTTPSamplerProxy)
            // TODO(jmx2gatling) #1 Script pre-processor not converted [JSR223PreProcessor]
            // (original shown at the first #1 marker and in conversion-report.md)
            http("GET /home").get("/home")
                .header("X-Team", "tg-team")
                .queryParam("locale", "en-US")
                .disableFollowRedirect()
                .check(status().is(200))
        );

    {
        setUp(
            // Injection for TestPlan > Scoped Users (ThreadGroup)
            scopedUsers.injectOpen(rampUsers(3).during(Duration.ofSeconds(3)))
        ).protocols(httpProtocol);
    }
}
