package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 03-disabled-subtrees.jmx.
 * Conversion notes: see conversion-report.md (0 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx03DisabledSubtreesSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "http://status.example-disabled.test");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Active Flow (ThreadGroup)
    private final ScenarioBuilder activeFlow = scenario("Active Flow")
        .exec(
            // GET /health (HTTPSamplerProxy)
            http("GET /health").get("/health")
        );

    {
        setUp(
            // Injection for TestPlan > Active Flow (ThreadGroup)
            activeFlow.injectOpen(rampUsers(2).during(Duration.ofSeconds(4)))
        ).protocols(httpProtocol);
    }
}
