package golden;

import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import java.time.Duration;

/**
 * Generated by jmx2gatling from 10-multi-threadgroups-setup-teardown.jmx.
 * Conversion notes: see conversion-report.md (0 TODOs).
 * Target: Gatling 3.16.0 Java DSL.
 */
public class Jmx10MultiThreadgroupsSetupTeardownSimulation extends Simulation {

    // Override with -DbaseUrl=...
    private static final String BASE_URL = System.getProperty("baseUrl", "https://groups.example-groups.test");

    // No HTTP Cache Manager in the plan, so caching is disabled as in JMeter
    private final HttpProtocolBuilder httpProtocol = http
        .baseUrl(BASE_URL)
        .disableCaching()
        .disableWarmUp()
        ;

    // TestPlan > Seed Data (SetupThreadGroup)
    private final ScenarioBuilder seedData = scenario("Seed Data")
        .exec(
            // POST /admin/seed (HTTPSamplerProxy)
            http("POST /admin/seed").post("/admin/seed")
        );

    // TestPlan > Browsers (ThreadGroup)
    private final ScenarioBuilder browsers = scenario("Browsers")
        .exec(
            // Thread group loop count
            repeat(3).on(
                // GET /browse (HTTPSamplerProxy)
                http("GET /browse").get("/browse")
            )
        );

    // TestPlan > Buyers (ThreadGroup)
    private final ScenarioBuilder buyers = scenario("Buyers")
        .exec(
            // Thread group loop count
            repeat(2).on(
                // POST /buy (HTTPSamplerProxy)
                http("POST /buy").post("/buy")
            )
        );

    // TestPlan > Browsers (ThreadGroup)
    private final ScenarioBuilder browsers2 = scenario("Browsers (2)")
        .exec(
            // GET /browse/again (HTTPSamplerProxy)
            http("GET /browse/again").get("/browse/again")
        );

    // TestPlan > Cleanup (PostThreadGroup)
    private final ScenarioBuilder cleanup = scenario("Cleanup")
        .exec(
            // POST /admin/cleanup (HTTPSamplerProxy)
            http("POST /admin/cleanup").post("/admin/cleanup")
        );

    {
        setUp(
            // Injection for TestPlan > Seed Data (SetupThreadGroup)
            seedData.injectOpen(rampUsers(1).during(Duration.ofSeconds(1)))
                .andThen(
                    // Injection for TestPlan > Browsers (ThreadGroup)
                    browsers.injectOpen(rampUsers(20).during(Duration.ofSeconds(10)))
                        .andThen(
                            // Injection for TestPlan > Cleanup (PostThreadGroup)
                            cleanup.injectOpen(rampUsers(1).during(Duration.ofSeconds(1)))
                        ),
                    // Injection for TestPlan > Buyers (ThreadGroup)
                    buyers.injectOpen(rampUsers(5).during(Duration.ofSeconds(10))),
                    // Injection for TestPlan > Browsers (ThreadGroup)
                    browsers2.injectOpen(rampUsers(1).during(Duration.ofSeconds(1)))
                )
        ).protocols(httpProtocol);
    }
}
